[package]
name = "sky130_commercial_pdk"
version = "0.1.0"
edition = "2021"
authors = ["Rahul Kumar <rahulkumar@berkeley.edu>"]

[dependencies]
substrate = { path = "../../substrate" }
arcstr = "1"
sky130_common_pdk = { path = "../sky130_common_pdk" }
