[package]
name = "sky130_common_pdk"
version = "0.1.0"
edition = "2021"
authors = ["Rahul Kumar <rahulkumar@berkeley.edu>", "Rohan Kumar <rohankumar@berkeley.edu>"]

[dependencies]
substrate = { path = "../../substrate" }
subgeom = { path = "../../libs/subgeom" }
arcstr = "1"
